### ISSUE TITLE
[QST] Dockerized integration tests

### ISSUE THREAD

**Issue by randerzander** [rapidsai/integration#243]
As RAPIDS deployment scenarios have grown, we have customers integrating with Apache Hive & Apache Kafka.

I believe we decided we didn't want GPU CI to have to spin up "heavy" services for integration tests, and so they needed someplace else to live.

The name `rapidsai/integration` suggests it's a potential home for them, but it looks like integration tests are limited to software installable from conda.

Can we consider adding Docker container tests here, or should we continue self-supporting these Hive and Kafka tests?

cc @beckernick @jdye64 @kevingerman

**Comment by mike-wendt** [comment]
Will setup a discussion for this shortly

**Comment by randerzander** [comment]
@raydouglass can we discuss after release, please?

**Comment by bdice** [comment]
Closing as stale.
