### ISSUE TITLE
Package naming conflict

### ISSUE THREAD

**Issue by dxm447** [rapidsai/integration#379]
There are two **rapids** packages, one from the [rapidsai channel](https://anaconda.org/rapidsai/rapids), and another from the [conda-forge channel](https://anaconda.org/conda-forge/rapids). For some reason, conda wants to install the latter rather than the former in some cases.

**Comment by bdice** [comment]
I would suspect that this happened because of some conflict between the existing environment and the contents of the `rapids` metapackage. However, this is about two years stale, so I will close. For current installation instructions, please visit https://docs.rapids.ai/install.
