### ISSUE TITLE
UnsatisfiableError : Conda will not install Rapids

### ISSUE THREAD

**Issue by AlexNguyen124** [rapidsai/integration#381]
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - rapids-blazing=21.10 -> cudatoolkit=11.4 -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.31

**Comment by bdice** [comment]
Closing as stale. For current installation instructions, please visit https://docs.rapids.ai/install.
