### ISSUE TITLE
Python 3.10 conda install error?

### ISSUE THREAD

**Issue by nkuehnle** [rapidsai/integration#451]
Currently getting this issue when trying to install rapids alongside python 3.10. Is rapids really incompatible or is this a packaging issue on the Conda end? The 3.1 request strikes me as an error.
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

ResolvePackageNotFound: 
  - python=3.1
 ```

**Comment by thorstenwagner** [comment]
I would also appreciate if rapids would support python 3.10

**Comment by raydouglass** [comment]
We are adding Python 3.10 support in release 23.02 due out next week.

**Comment by bdice** [comment]
Closing as complete.
